[book]
authors = ["Raimi"]
language = "en"
multilingual = false
src = "src"
title = "Spring Boot"

[output.html.playground]
editable = true

[output.html]
site-url = "/books/spring-boot/"

[build]
build-dir = "../../spring-boot"
