[book]
authors = ["remykarem"]
language = "en"
multilingual = false
src = "src"
title = "Stats book"

[output.html]
site-url = "/books/stats-book/"
mathjax-support = true
# Required for preprocess.last-changed
git-repository-url = "https://github.com/remykarem/remkarem.github.io"
additional-css = ["last-changed.css"]

[build]
build-dir = "../../stats-book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]
