[book]
authors = ["Raimi"]
language = "en"
multilingual = false
src = "src"
title = "networking-book"

[output.html.playground]
editable = true

[output.html]
site-url = "/books/networking-book/"

[build]
build-dir = "../../networking-book"
