[book]
authors = ["Raimi"]
language = "en"
multilingual = false
src = "src"
title = "ai-book"

[output.html]
site-url = "/books/ai-book/"
mathjax-support = true

[build]
build-dir = "../../ai-book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
