[book]
authors = ["Raimi"]
language = "en"
multilingual = false
src = "src"
title = "AI/ML/DS book"

[output.html]
site-url = "/books/ai-book/"
mathjax-support = true
# Required for preprocess.last-changed
git-repository-url = "https://github.com/remykarem/remkarem.github.io"
additional-css = ["last-changed.css"]

[build]
build-dir = "../../ai-book"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]
