name: Build and Deploy mdBooks

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.30'

    - name: Build networking book
      run: |
        mdbook build books/networking-book

    # Add more build steps as needed for each book

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./books
