name: Build and Deploy mdBooks

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.30'

    - name: Download mdbook preprocessors
      run: |
        curl -O -L https://github.com/tommilligan/mdbook-admonish/releases/download/v1.9.0/mdbook-admonish-v1.13.0-x86_64-unknown-linux-musl.tar.gz
        tar xvzf mdbook-admonish-v1.9.0-x86_64-unknown-linux-musl.tar.gz -C ~/.cargo/bin
        curl -O -L https://github.com/lzanini/mdbook-katex/releases/download/v0.3.15/mdbook-katex-v0.3.15-x86_64-unknown-linux-musl.tar.gz
        tar xvzf mdbook-katex-v0.3.15-x86_64-unknown-linux-musl.tar.gz -C ~/.cargo/bin
        curl -O -L https://github.com/badboy/mdbook-mermaid/releases/download/v0.12.6/mdbook-mermaid-v0.12.6-x86_64-unknown-linux-musl.tar.gz
        tar xvzf mdbook-mermaid-v0.12.6-x86_64-unknown-linux-musl.tar.gz -C ~/.cargo/bin
        rm mdbook-*

    - name: Build books
      run: |
        mdbook build books-src/number-theory-book
        mdbook build books-src/system-design-book
        mdbook build books-src/spring-boot-book
        mdbook build books-src/db-book
        mdbook build books-src/security-book
        mdbook build books-src/swift-book
        mdbook build books-src/the-art-of-coding-book
        mdbook build books-src/rust-book
        mdbook build books-src/c-book
        mdbook build books-src/shell-book
        mdbook build books-src/networking-book
        mdbook build books-src/cryptography-book
        mdbook build books-src/os-book
        mdbook build books-src/data-structures-and-algorithms-book

    # Add more build steps as needed for each book

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Which directory to serve the pages after
        # successful build
        publish_dir: ./
